### ISSUE TITLE
Error: this.toObject is not a function

### ISSUE THREAD

**Issue by lukascamargo** [taylanken/mongoose-version-history#5]
Hi! How are you doing?

I tried to save using the mongoose update code as it shows below, but it came out with an TypeError in mongoose-version-history

The Code:
`Internalizacao
                    .update({ _id: req.params.id }, { $set: parametro }, function (err, resposta) {
                        if (err) {
                            console.log(err)
                            return callback(err, null)
                        } else {
                            console.log('3 - updated')
                            return callback(null, resposta)
                        }
                    })`

Error:
`events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: this.toObject is not a function
    at model.Query.<anonymous> (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose-version-history\index.js:110:31)
    at next (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\kareem\index.js:82:14)
    at Kareem.execPre (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\kareem\index.js:99:3)
    at Kareem.wrap (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\kareem\index.js:240:8)
    at model.Query._execUpdate (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\kareem\index.js:285:11)
    at _update (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose\lib\query.js:2685:20)
    at model.Query.Query.update (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose\lib\query.js:2449:10)
    at _update (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose\lib\model.js:2370:16)
    at Function.update (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose\lib\model.js:2280:10)
    at update (C:\Users\lukas.camargo\Documents\Stack\Code\stack\app\api\internalizacao\update.js:135:22)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:3686:9
    at replenish (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:881:17)
    at iterateeCallback (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:866:17)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:843:16
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:3691:13
    at apply (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:21:25)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:56:12
    at createOrUpdateDelivery (C:\Users\lukas.camargo\Documents\Stack\Code\stack\app\api\internalizacao\update.js:114:24)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:3686:9
    at replenish (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:881:17)
    at iterateeCallback (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:866:17)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:843:16
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:3691:13
    at apply (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:21:25)
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\async\dist\async.js:56:12
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\app\api\internalizacao\update.js:84:32
    at C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mongoose\lib\query.js:2741:18
    at newTickHandler (C:\Users\lukas.camargo\Documents\Stack\Code\stack\node_modules\mpromise\lib\promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

Could you help me with it?

Thanks and regards.

**Comment by ViljarVoidula** [comment]
+1
